name: Build FFmpeg 3.4.8 for Android (armeabi-v7a)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout FFmpeg source
        uses: actions/checkout@v4

      - name: Set up Android SDK and NDK
        uses: android-actions/setup-android@v3
        with:
          sdk-version: 9123335

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake build-essential cmake git libtool pkg-config curl

      - name: Prepare NDK and PATH
        run: |
          export ANDROID_NDK=$HOME/android-sdk/ndk/21.4.7075529
          echo "ANDROID_NDK=$ANDROID_NDK" >> $GITHUB_ENV
          echo "$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

      - name: Add gas-preprocessor (needed for old FFmpeg)
        run: |
          sudo curl -L https://raw.githubusercontent.com/FFmpeg/gas-preprocessor/master/gas-preprocessor.pl -o /usr/local/bin/gas-preprocessor.pl
          sudo chmod +x /usr/local/bin/gas-preprocessor.pl

      - name: Configure FFmpeg
        run: |
          chmod +x configure
          ./configure \
            --prefix=$PWD/build/armeabi-v7a \
            --target-os=android \
            --arch=arm \
            --cpu=armv7-a \
            --cross-prefix=arm-linux-androideabi- \
            --sysroot=$HOME/android-sdk/ndk/21.4.7075529/platforms/android-21/arch-arm \
            --enable-cross-compile \
            --enable-shared \
            --disable-static \
            --disable-doc \
            --disable-programs \
            --enable-small \
            --disable-avdevice \
            --disable-postproc \
            --disable-symver \
            --disable-ffplay \
            --disable-ffmpeg \
            --disable-ffprobe \
            --disable-network \
            --disable-bsfs \
            --disable-filters \
            --disable-debug

      - name: Build FFmpeg
        run: |
          make -j$(nproc)
          make install

      - name: Upload compiled .so and headers
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-android-libs
          path: build/armeabi-v7a

