name: Build FFmpeg 3.4.8 Android ARMv7

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip make yasm nasm build-essential
          
      - name: Download NDK r21e
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
          unzip -q android-ndk-r21e-linux-x86_64.zip
          
      - name: Download FFmpeg 3.4.8
        run: |
          wget https://ffmpeg.org/releases/ffmpeg-3.4.8.tar.bz2
          tar -xjf ffmpeg-3.4.8.tar.bz2
          
      - name: Configure and Build FFmpeg
        run: |
          cd ffmpeg-3.4.8
          
          export NDK=$PWD/../android-ndk-r21e
          export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
          export API=16
          export TARGET=armv7a-linux-androideabi
          
          export CC=$TOOLCHAIN/bin/${TARGET}${API}-clang
          export CXX=$TOOLCHAIN/bin/${TARGET}${API}-clang++
          export AR=$TOOLCHAIN/bin/arm-linux-androideabi-ar
          export AS=$TOOLCHAIN/bin/arm-linux-androideabi-as
          export LD=$TOOLCHAIN/bin/arm-linux-androideabi-ld
          export RANLIB=$TOOLCHAIN/bin/arm-linux-androideabi-ranlib
          export STRIP=$TOOLCHAIN/bin/arm-linux-androideabi-strip
          export NM=$TOOLCHAIN/bin/arm-linux-androideabi-nm
          
          ./configure \
            --prefix=$PWD/../build/armeabi-v7a \
            --enable-cross-compile \
            --target-os=android \
            --arch=arm \
            --cpu=armv7-a \
            --cc=$CC \
            --cxx=$CXX \
            --ar=$AR \
            --ranlib=$RANLIB \
            --strip=$STRIP \
            --nm=$NM \
            --extra-cflags="-O3 -fPIC -march=armv7-a -mfpu=neon -mfloat-abi=softfp" \
            --extra-ldflags="-Wl,--fix-cortex-a8" \
            --enable-shared \
            --disable-static \
            --disable-doc \
            --disable-programs \
            --disable-ffmpeg \
            --disable-ffplay \
            --disable-ffprobe \
            --disable-ffserver \
            --disable-avdevice \
            --disable-postproc \
            --enable-network \
            --enable-protocol=file \
            --enable-protocol=http \
            --enable-protocol=https \
            --enable-protocol=tcp \
            --enable-protocol=udp \
            --enable-protocol=rtp \
            --enable-protocol=rtmp \
            --enable-avfilter \
            --enable-pic \
            --enable-small \
            --enable-neon
          
          make -j$(nproc)
          make install
          
      - name: Verify libraries
        run: |
          echo "Built libraries:"
          ls -lh build/armeabi-v7a/lib/
          file build/armeabi-v7a/lib/*.so*
          
      - name: Package output
        run: |
          mkdir -p output/lib/armeabi-v7a
          mkdir -p output/include
          cp build/armeabi-v7a/lib/*.so* output/lib/armeabi-v7a/
          cp -r build/armeabi-v7a/include/* output/include/
          
          cd output
          tar -czf ../ffmpeg-3.4.8-android-armv7.tar.gz .
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-3.4.8-android-armv7
          path: |
            ffmpeg-3.4.8-android-armv7.tar.gz
            output/lib/armeabi-v7a/*.so*
            output/include/
