name: Build FFmpeg 3.4.8 Android ARMv7

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip make yasm autoconf automake libtool pkg-config curl

      - name: Download Android NDK r16b
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip
          unzip -q android-ndk-r16b-linux-x86_64.zip
          echo "ANDROID_NDK=$PWD/android-ndk-r16b" >> $GITHUB_ENV
          echo "$PWD/android-ndk-r16b" >> $GITHUB_PATH

      - name: Add gas-preprocessor
        run: |
          sudo curl -L https://raw.githubusercontent.com/FFmpeg/gas-preprocessor/master/gas-preprocessor.pl -o /usr/local/bin/gas-preprocessor.pl
          sudo chmod +x /usr/local/bin/gas-preprocessor.pl

      - name: Fix permissions
        run: |
          chmod +x configure
          chmod -R +x ffbuild

      - name: Configure FFmpeg
        run: |
          export ANDROID_NDK=$PWD/android-ndk-r16b
          export TOOLCHAIN=$ANDROID_NDK/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64
          export SYSROOT=$ANDROID_NDK/platforms/android-16/arch-arm
          export PATH=$TOOLCHAIN/bin:$PATH
          export CROSS_PREFIX=arm-linux-androideabi-
          export CC="${CROSS_PREFIX}gcc --sysroot=$SYSROOT"
          export CXX="${CROSS_PREFIX}g++ --sysroot=$SYSROOT"
          export LD="${CROSS_PREFIX}ld"
          export AS="gas-preprocessor.pl -- ${CC}"
          ./configure \
            --prefix=$PWD/build/armeabi-v7a \
            --target-os=android \
            --arch=arm \
            --cpu=armv7-a \
            --enable-cross-compile \
            --cross-prefix=$CROSS_PREFIX \
            --sysroot=$SYSROOT \
            --enable-shared \
            --disable-static \
            --disable-doc \
            --disable-programs \
            --disable-ffmpeg \
            --disable-ffplay \
            --disable-ffprobe \
            --disable-network \
            --disable-avdevice

      - name: Build
        run: |
          export ANDROID_NDK=$PWD/android-ndk-r16b
          export TOOLCHAIN=$ANDROID_NDK/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64
          export PATH=$TOOLCHAIN/bin:$PATH
          make -j$(nproc)

      - name: Install
        run: make install

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-3.4.8-armv7
          path: build/armeabi-v7a
