      - name: Configure FFmpeg
        run: |
          export ANDROID_NDK=$PWD/android-ndk-r16b
          export TOOLCHAIN=$ANDROID_NDK/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64
          export SYSROOT=$ANDROID_NDK/platforms/android-16/arch-arm
          export PATH=$TOOLCHAIN/bin:$PATH
          export CROSS_PREFIX=arm-linux-androideabi-
          export CC="${CROSS_PREFIX}gcc --sysroot=$SYSROOT"
          export CXX="${CROSS_PREFIX}g++ --sysroot=$SYSROOT"
          export LD="${CROSS_PREFIX}ld"
          export AS="gas-preprocessor.pl -- ${CC}"

          ./configure \
            --prefix=$PWD/build/armeabi-v7a \
            --target-os=android \
            --arch=arm \
            --cpu=armv7-a \
            --enable-cross-compile \
            --cross-prefix=$CROSS_PREFIX \
            --sysroot=$SYSROOT \
            --extra-cflags="-isysroot $SYSROOT/usr/include -I$SYSROOT/usr/include -march=armv7-a" \
            --extra-ldflags="-L$SYSROOT/usr/lib" \
            --enable-shared \
            --disable-static \
            --disable-doc \
            --disable-programs \
            --disable-ffmpeg \
            --disable-ffplay \
            --disable-ffprobe \
            --disable-network \
            --disable-avdevice
